name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: none, mbstring
        tools: none
